name: Oracle Capacity Bot

on:
  workflow_dispatch:
  # schedule:
  #   - cron: '*/5 * * * *'

jobs:
  provision:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Install dependencies
        run: composer install --no-dev --optimize-autoloader

      - name: Create Private Key File
        run: |
          cat << 'EOF' > private_key.pem
          ${{ secrets.OCI_PRIVATE_KEY }}
          EOF

      - name: Test Secret Visibility
        run: |
          if [ -z "${{ secrets.OCI_REGION }}" ]; then
            echo "❌ ERROR: GitHub cannot see the Region secret. It is completely blank."
            exit 1
          else
            echo "✅ SUCCESS: GitHub can see the secret!"
          fi

      - name: Run the bot
        run: |
          DELAY=$((RANDOM % 180 + 1))
          echo "Randomizing execution: Pausing for $DELAY seconds..."
          sleep $DELAY
          php ./index.php
        env:
          OCI_REGION: ${{ secrets.OCI_REGION }}
          OCI_TENANCY_ID: ${{ secrets.OCI_TENANCY_ID }}
          OCI_USER_ID: ${{ secrets.OCI_USER_ID }}
          OCI_KEY_FINGERPRINT: ${{ secrets.OCI_KEY_FINGERPRINT }}
          OCI_PRIVATE_KEY_FILENAME: private_key.pem
          OCI_COMPARTMENT_ID: ${{ secrets.OCI_COMPARTMENT_ID }}
          OCI_SUBNET_ID: ${{ secrets.OCI_SUBNET_ID }}
          OCI_IMAGE_ID: ${{ secrets.OCI_IMAGE_ID }}
          OCI_OCPUS: ${{ secrets.OCI_OCPUS }}
          OCI_MEMORY_IN_GBS: ${{ secrets.OCI_MEMORY_IN_GBS }}
          OCI_SHAPE: "VM.Standard.A1.Flex"
          OCI_MAX_INSTANCES: 2
          OCI_SSH_PUBLIC_KEY: ${{ secrets.OCI_SSH_PUBLIC_KEY }}
